import fs from 'fs';

const enPath = './src/locales/en.json';
const jaPath = './src/locales/ja.json';

const en = JSON.parse(fs.readFileSync(enPath, 'utf-8'));

// 一括翻訳マッピング（Obsidian用語集および自然な日本語）
const manualTranslations = {
  "  {index}. Line {line}: {content}": "  {index}. 行 {line}: {content}",
  " ({min}-{max}, lower is better quality).": " ({min}-{max}、小さいほど高品質)。",
  "_attachments → Skips that folder and everything inside it": "_attachments → そのフォルダと内部のすべてをスキップ",
  "_attachments/* → Skips only direct children in that folder": "_attachments/* → そのフォルダ直下の項目のみをスキップ",
  "_attachments/** → Skips that folder and all nested subfolders": "_attachments/** → そのフォルダとすべての階層のサブフォルダをスキップ",
  ". CRF range: {min}-{max}": "。CRF範囲: {min}-{max}",
  ". This ensures the link works from any note in your vault, regardless of its location.": "。これにより、保管庫内のどのノートからでも配置場所に関係なくリンクが正しく機能します。",
  "(Height: {height})": "(高さ: {height})",
  "(Longest Edge: {edge})": "(長辺: {edge})",
  "(Shortest Edge: {edge})": "(短辺: {edge})",
  "(Width: {width})": "(幅: {width})",
  "{type} Preset: {name}": "{type} プリセット: {name}",
  "{Variables}": "{変数}",
  "/_attachments → Same as above": "/_attachments → 上記と同様",
  "/^_attachments\\\\// → Skips paths starting with _attachments/": "/^_attachments\\\\// → _attachments/ で始まるパスをスキップ",
  "• Reduce and enlarge: adjusts all images to fit specified dimensions\\n• Reduce only: only shrinks images larger than target\\n• Enlarge only: only enlarges images smaller than target": "• 縮小と拡大: 指定サイズに合わせてすべての画像を調整\n• 縮小のみ: ターゲットより大きい画像のみを縮小\n• 拡大のみ: ターゲットより小さい画像のみを拡大",
  "• Reduce and enlarge: Adjusts all images to fit specified dimensions\\n• Reduce only: Only shrinks images larger than target\\n• Enlarge only: Only enlarges images smaller than target": "• 縮小と拡大: 指定サイズに合わせてすべての画像を調整\n• 縮小のみ: ターゲットより大きい画像のみを縮小\n• 拡大のみ: ターゲットより小さい画像のみを拡大",
  "→ Path becomes:": "→ 変換後のパス:",
  "+ Add new": "+ 新規追加",
  "⚠️ This will modify all images in the current note — please ensure you have backups.": "⚠️ 現在のノート内のすべての画像が変更されます。必ず事前にバックアップをご確認ください。",
  "⚠️ This will modify all images in the selected folder and subfolders (if recursive is enabled). Please ensure you have backups.": "⚠️ 選択したフォルダおよびサブフォルダ内のすべての画像が変更されます（再帰処理が有効な場合）。必ず事前にバックアップをご確認ください。",
  "⚠️ This will modify all images in the vault. Please ensure you have backups.": "⚠️ 保管庫内のすべての画像が変更されます。必ず事前にバックアップをご確認ください。",
  "✓ Working encoder: {encoder}{hint}": "✓ 動作可能なエンコーダー: {encoder}{hint}",
  "✓ Working encoder: {encoder}{platformHint}": "✓ 動作可能なエンコーダー: {encoder}{platformHint}",
  "📂 Folder": "📂 フォルダ",
  "📄 Filename": "📄 ファイル名",
  "📄 Note location:": "📄 ノートの場所:",
  "🖼️ Image location:": "🖼️ 画像の場所:",
  "1 Line below the image": "画像の1行下",
  "100: no compression (original quality)\\n75: recommended (good balance)\\n0-50: high compression (lower quality)": "100: 圧縮なし（元の品質）\n75: 推奨（品質とサイズのバランス）\n0-50: 高圧縮（低品質）",
  "100: No compression (original quality)\\n75: Recommended (good balance)\\n0-50: High compression (lower quality)": "100: 圧縮なし（元の品質）\n75: 推奨（品質とサイズのバランス）\n0-50: 高圧縮（低品質）",
  "90° clockwise": "時計回りに90°",
  "90° counter clockwise": "反時計回りに90°",
  "A comma-separated list of file names or patterns that the plugin should never process. Supports glob (*) and regex (enclosed in `/` or `r/` or `regex:`). E.g., `old.png, /^_/, r/temp-.*\\\\.jpg$/` . Or simply skip all cat images e.g.: /cat/ or all gif images *.gif": "処理から除外するファイル名またはパターンのカンマ区切りリスト。Glob（*）および正規表現（`/`、`r/`、`regex:` で囲む）に対応しています。例: `old.png, /^_/, r/temp-.*\\\\.jpg$/`、すべての猫画像をスキップする場合は `/cat/`、GIF画像全体なら `*.gif`。",
  "A preset with this name already exists.": "この名前のプリセットは既に存在します。",
  "Absolute": "絶対パス",
  "Absolute:": "絶対パス:",
  "Add": "追加",
  "Add number suffix (-1, -2, etc.)": "連番サフィックスを追加 (-1, -2 など)",
  "Add Text (T)": "テキスト追加 (T)",
  "Adjust how sensitive the scroll-wheel resize is (0.01-1.0)": "スクロールホイールによるリサイズの感度を調整します (0.01〜1.0)",
  "Advanced (regex):": "高度な設定 (正規表現):",
  "all images in: {filename}": "対象のすべての画像: {filename}",
  "all images in: /{folderName}": "対象のすべての画像: /{folderName}",
  "Allow larger files": "元のサイズより大きくなることを許可",
  "Allow Larger Files: {allow}": "大きいファイルを許可: {allow}",
  "Allow resizing images by dragging edges of the image.": "画像の端をドラッグしてサイズ変更できるようにします。",
  "Allow resizing images using the scroll wheel": "スクロールホイールを使用した画像のサイズ変更を許可します",
  "Allow resizing in reading mode": "閲覧モードでのリサイズを許可",
  "Always show": "常に表示",
  "An unexpected error occurred. Check console for details.": "予期しないエラーが発生しました。詳細はコンソールを確認してください。",
  "Annotate image": "画像に注釈を追加",
  "Apply": "適用",
  "Apply original image height": "元の画像の高さを適用",
  "Apply original image width": "元の画像の幅を適用",
  "archive/2025/** → Skips a specific folder tree": "archive/2025/** → 特定のフォルダツリー全体をスキップ",
  "Are you sure you want to delete the global preset \"{name}\"?": "グローバルプリセット「{name}」を削除してもよろしいですか？",
  "Are you sure you want to delete the preset \"{name}\"?": "プリセット「{name}」を削除してもよろしいですか？",
  "Arrow (A)": "矢印 (A)",
  "Ask each time": "毎回確認する",
  "At the back of the link": "リンクの末尾",
  "At the front of the link": "リンクの先頭",
  "Auto": "自動",
  "Auto-detect FFmpeg": "FFmpegを自動検出",
  "Automatically apply this alignment when inserting new images. Set to 'none' to disable.": "新しい画像を挿入する際にこの配置を自動適用します。「なし」に設定すると無効になります。",
  "Available variables": "利用可能な変数",
  "AVIF (via ffmpeg)": "AVIF (FFmpeg経由)",
  "Background": "背景",
  "Background color": "背景色",
  "Blend:": "ブレンド:",
  "Bold": "太字",
  "Border": "枠線",
  "Border corner radius": "枠線の角丸",
  "Bring Forward": "前面へ移動",
  "Bring to Front": "最前面へ移動",
  "Burn": "焼き込み",
  "Cancel": "キャンセル",
  "Capitalize": "先頭文字を大文字化",
  "Caption:": "キャプション:",
  "Captions": "キャプション",
  "Center": "中央揃え",
  "Choose a background color for image captions (e.g.: Transparent, #f5f5f5, rgba(255,255,255,0.8))": "画像キャプションの背景色を選択します (例: Transparent, #f5f5f5, rgba(255,255,255,0.8))",
  "Choose a color for image captions e.g.: Red, grey, white, black, hsl(50, 50%, 50%), rgb(50%, 75%, 100%) ": "画像キャプションの文字色を選択します (例: Red, grey, white, black, hsl(50, 50%, 50%), rgb(50%, 75%, 100%))",
  "Choose between wikilink and Markdown format": "内部リンク（Wikilink）形式かMarkdown形式を選択します",
  "Choose how images should be resized - results are permanent.": "画像のリサイズ方法を選択します（恒久的に適用されます）。",
  "Choose how images should be resized. Note: results are permanent": "画像のリサイズ方法を選択します（注意: 恒久的に適用されます）",
  "Choose how images should be resized. Note: Results are permanent": "画像のリサイズ方法を選択します（注意: 恒久的に適用されます）",
  "Choose how paths should be formatted": "パスのフォーマット形式を選択します",
  "Choose how to handle filename conflicts": "ファイル名の競合時の処理方法を選択します",
  "Choose how to resize the image": "画像のリサイズ方法を選択します",
  "Choose output format for your images": "画像の出力フォーマットを選択します",
  "Choose output format. 'Same as original' applies compression/resizing to current format.": "出力フォーマットを選択します。「元の形式を維持」は現在のフォーマットのまま圧縮/リサイズを適用します。",
  "Choose output format. Same as original applies compression/resizing to current format": "出力フォーマットを選択します。「元の形式を維持」は現在のフォーマットのまま圧縮/リサイズを適用します",
  "Choose where to store the cache file for image alignments. Note: App reload required.": "画像の配置情報のキャッシュ保存先を選択します（注意: アプリの再読み込みが必要です）。",
  "Choose whether to show processing options on each image drop/paste": "画像のドロップ/貼り付け時に処理オプションを表示するかどうかを選択します",
  "Clear all": "すべてクリア",
  "Click to copy variable name": "クリックして変数名をコピー",
  "Click to load, Shift+Click to save": "クリックで読み込み、Shift+クリックで保存",
  "Color": "色",
  "Color depth": "色深度",
  "Color Depth: {depth}": "色深度: {depth}",
  "Comma-separated list of patterns to skip (glob or regex). Regex patterns must be enclosed in `/` or `r/` or `regex:` E.g. do not process images which include word CAT in them /CAT/": "スキップするパターンのカンマ区切りリスト（Globまたは正規表現）。正規表現パターンは `/`、`r/`、または `regex:` で囲む必要があります（例: 「CAT」を含む画像を除外する場合は `/CAT/`）。",
  "Constant rate factor for ": "固定品質係数（CRF）: ",
  "Constant rate factor for AVIF (0-63, lower is better quality). Range varies by encoder - click 'Detect encoder' to see the specific range.": "AVIFの固定品質係数（0〜63、小さいほど高品質）。範囲はエンコーダーによって異なります。「エンコーダーを検出」をクリックして固有の範囲を確認してください。",
  "Conversion": "変換",
  "Conversion Settings": "変換設定",
  "Copied!": "コピーしました！",
  "Crop": "トリミング",
  "Crop image": "画像をトリミング",
  "Crop Image": "画像のトリミング",
  "Current Note": "現在のノート",
  "Current note ({count} images)": "現在のノート ({count} 件の画像)",
  "Current note (0 images)": "現在のノート (画像なし)",
  "Cursor position after drop/paste": "ドロップ/貼り付け後のカーソル位置",
  "Cursor position during resize": "リサイズ中のカーソル位置",
  "Custom": "カスタム",
  "Custom (WidthxHeight)": "カスタム (幅x高さ)",
  "Custom dimensions template": "カスタム寸法テンプレート",
  "Custom imagename": "カスタム画像名",
  "Custom location: {template}": "カスタム保存先: {template}",
  "Custom name": "カスタム名",
  "Custom path": "カスタムパス",
  "Custom value": "カスタム値",
  "Custom: {custom}": "カスタム: {custom}",
  "Deselect": "選択解除",
  "Desired height": "希望する高さ",
  "Desired longest edge": "希望する長辺サイズ",
  "Desired shortest edge": "希望する短辺サイズ",
  "Desired width": "希望する幅",
  "Detect and validate working AV1 encoder by running a test encode. This ensures hardware encoders are actually available on your system.": "テストエンコードを実行して動作可能なAV1エンコーダーを検出し検証します。これによりシステムでハードウェアエンコーダーが実際に使用可能か確認できます。",
  "Detect encoder": "エンコーダーを検出",
  "Dimension": "寸法",
  "Dimensions": "寸法",
  "Dimensions:": "寸法:",
  "Disable Obsidian image selection on click": "クリック時のObsidian標準画像選択を無効化",
  "Disabled": "無効",
  "Display text template": "表示テキストテンプレート",
  "Do not change": "変更しない",
  "Do not process": "処理しない",
  "Do not resize": "リサイズしない",
  "Edge": "辺",
  "Editor max width": "エディタの最大幅",
  "Editor Max Width: {width}": "エディタ最大幅: {width}",
  "Empty folder name. Please enter a valid folder name.": "フォルダ名が空です。有効なフォルダ名を入力してください。",
  "Empty template. Please enter a valid template.": "テンプレートが空です。有効なテンプレートを入力してください。",
  "Enable drag resize": "ドラッグによるリサイズを有効化",
  "Enable scroll-wheel resize": "スクロールホイールによるリサイズを有効化",
  "Encoder detection": "エンコーダーの検出",
  "Encoder detection failed. Using cached encoder: {encoder}{hint}": "エンコーダーの検出に失敗しました。キャッシュされたエンコーダーを使用します: {encoder}{hint}",
  "Encoder detection failed. Using cached encoder: {encoder}{platformHint}": "エンコーダーの検出に失敗しました。キャッシュされたエンコーダーを使用します: {encoder}{platformHint}",
  "Encoding preset (speed vs. compression).": "エンコードプリセット（処理速度 vs 圧縮率）。",
  "Encoding preset for {encoder} (speed vs. compression).": "{encoder} のエンコードプリセット（処理速度 vs 圧縮率）。",
  "Enlarge Only": "拡大のみ",
  "Enlarge/Reduce: {mode}": "拡大/縮小: {mode}",
  "Enter folder name": "フォルダ名を入力",
  "Enter preset name": "プリセット名を入力",
  "Eraser (E)": "消しゴム (E)",
  "Error detecting encoder: {message}": "エンコーダー検出エラー: {message}",
  "Error: active file not found": "エラー: アクティブなファイルが見つかりません",
  "Error: destination folder cannot be empty": "エラー: 保存先フォルダを指定してください",
  "Error: failed to get image dimensions": "エラー: 画像の寸法を取得できませんでした",
  "Error: image dimensions could not be read": "エラー: 画像の寸法を読み取れませんでした",
  "Error: no images selected": "エラー: 画像が選択されていません",
  "Error: source file not found": "エラー: ソースファイルが見つかりません",
  "Examples": "設定例",
  "Examples:": "例:",
  "Executable path for pngquant": "pngquantの実行ファイルパス",
  "Export": "エクスポート",
  "Export Annotation": "注釈をエクスポート",
  "Export as new image": "新しい画像としてエクスポート",
  "Export image": "画像をエクスポート",
  "Failed to crop image": "画像のトリミングに失敗しました",
  "Failed to export annotation: {message}": "注釈のエクスポートに失敗しました: {message}",
  "Failed to process {count} image(s). Check console for details.": "{count} 件の画像の処理に失敗しました。詳細はコンソールを確認してください。",
  "Failed to process image: {message}": "画像の処理に失敗しました: {message}",
  "Failed to save preset": "プリセットの保存に失敗しました",
  "FFmpeg auto-detection failed: {message}": "FFmpegの自動検出に失敗しました: {message}",
  "FFmpeg CRF": "FFmpeg CRF",
  "FFmpeg executable path": "FFmpegの実行ファイルパス",
  "FFmpeg not found. Try installing via: Homebrew (macOS), Chocolatey (Windows), or apt/snap (Linux). Then set the path manually.": "FFmpegが見つかりませんでした。Homebrew (macOS)、Chocolatey (Windows)、または apt/snap (Linux) などでインストールし、手動でパスを設定してください。",
  "FFmpeg path detected and saved.": "FFmpegのパスを検出し保存しました。",
  "FFmpeg preset": "FFmpegプリセット",
  "FFmpeg Preset: {preset}": "FFmpegプリセット: {preset}",
  "Filename": "ファイル名",
  "Filename format": "ファイル名フォーマット",
  "Filename preset": "ファイル名プリセット",
  "Filename Presets": "ファイル名プリセット",
  "Fill": "塗りつぶし (Fill)",
  "Fit": "全体を収める (Fit)",
  "Fit editor max-width": "エディタの最大幅に合わせる",
  "Flip horizontal": "左右反転",
  "Flip vertical": "上下反転",
  "Folder": "フォルダ",
  "Folder preset": "フォルダプリセット",
  "Folder Presets": "フォルダプリセット",
  "Font size": "フォントサイズ",
  "Font style": "フォントスタイル",
  "Format": "フォーマット",
  "Format: {format}": "フォーマット: {format}",
  "Freeform": "自由比率",
  "Global Presets": "グローバルプリセット",
  "Height": "高さ",
  "Height: {height}": "高さ: {height}",
  "Highlight (H)": "ハイライト (H)",
  "If an output file already exists": "出力ファイルが既に存在する場合",
  "If an output file already exists: {resolution}": "出力ファイルが既に存在する場合: {resolution}",
  "If the processed image filesize is larger than the original, use the original image instead. Sometimes compression can increase file size, especially with certain formats or settings, but if you would prefer to always get smaller file sizes, enable this option.": "処理後の画像ファイルサイズが元画像より大きくなった場合、元画像をそのまま使用します。設定やフォーマットによって圧縮後にサイズが増加することがあるため、常にサイズ削減を優先したい場合はこのオプションを有効にしてください。",
  "Image Alignment": "画像の配置",
  "Image alignment cache cleanup interval": "画像配置キャッシュのクリーンアップ間隔",
  "Image alignment cache location": "画像配置キャッシュの保存先",
  "Image Captions": "画像キャプション",
  "Image converted: {name}": "画像を変換しました: {name}",
  "Image Converter": "Image Converter",
  "Image Converter Settings": "Image Converter 設定",
  "Image dimensions": "画像の寸法",
  "Image Drag and Resize": "画像のドラッグとリサイズ",
  "Image location": "画像の場所",
  "Image resized: {name}": "画像サイズを変更しました: {name}",
  "In subfolder: {template}": "サブフォルダ内: {template}",
  "Invalid custom value format. Use |widthxheight or percentage format (e.g., 50x75%).": "無効なカスタム形式です。|幅x高さ またはパーセンテージ形式（例: 50x75%）を使用してください。",
  "Italic": "斜体",
  "JPEG": "JPEG",
  "Keep original": "元画像を保持",
  "Keep original format": "元のフォーマットを維持",
  "Keep original name": "元のファイル名を維持",
  "Left": "左揃え",
  "Line (L)": "直線 (L)",
  "Link format": "リンク形式",
  "Link Format": "リンク形式",
  "Link format preset": "リンク形式プリセット",
  "Link format presets": "リンク形式プリセット",
  "Link type": "リンク種別",
  "Link Type: {linkFormat}, Path Type: {pathFormat}": "リンク種別: {linkFormat}、パス種別: {pathFormat}",
  "Link text": "リンクテキスト",
  "Location": "保存先",
  "Lock the aspect ratio when dragging": "ドラッグ時にアスペクト比を固定",
  "Longest edge": "長辺",
  "Longest Edge": "長辺",
  "Longest Edge: {edge}": "長辺: {edge}",
  "Lowercase": "小文字",
  "Maintain aspect ratio": "アスペクト比を維持",
  "Maintain Aspect Ratio: {val}": "アスペクト比を維持: {val}",
  "Markdown": "Markdown",
  "Max width value": "最大幅の値",
  "Medium": "標準",
  "Minimum compression savings (KB)": "最小圧縮削減量 (KB)",
  "Minimum compression savings (KB): {savings}": "最小圧縮削減量 (KB): {savings}",
  "Multiply": "乗算",
  "Never process these filenames": "除外するファイル名・パターン",
  "New preset": "新規プリセット",
  "No": "いいえ",
  "No images found": "画像が見つかりませんでした",
  "No images found in current note": "現在のノートに画像が見つかりませんでした",
  "No images found in folder: {folder}": "フォルダ内に画像が見つかりませんでした: {folder}",
  "No images found in vault": "保管庫内に画像が見つかりませんでした",
  "No resizing": "リサイズしない",
  "No working AV1 encoder found. Install FFmpeg with AV1 support.": "動作可能なAV1エンコーダーが見つかりませんでした。AV1対応のFFmpegをインストールしてください。",
  "No working encoder found. Install FFmpeg with libaom-av1, libsvtav1, or ensure hardware drivers are installed.": "動作可能なエンコーダーが見つかりませんでした。libaom-av1 や libsvtav1 対応のFFmpegをインストールするか、ハードウェアドライバを確認してください。",
  "None": "なし",
  "Normal": "通常",
  "Note location": "ノートの場所",
  "NoteName-Timestamp": "ノート名-タイムスタンプ",
  "Only Enlarge": "拡大のみ",
  "Only Reduce": "縮小のみ",
  "Opacity:": "不透明度:",
  "Open settings": "設定を開く",
  "Original height": "元の高さ",
  "Original size": "元のサイズ",
  "Original width": "元の幅",
  "Original Width": "元の幅",
  "Original Height": "元の高さ",
  "Output format": "出力フォーマット",
  "Overwrite": "上書き",
  "Padding": "パディング (余白)",
  "Paintbrush (B)": "ブラシ (B)",
  "Path format": "パス形式",
  "Pen (P)": "ペン (P)",
  "Pixels": "ピクセル",
  "Please enter a preset name.": "プリセット名を入力してください。",
  "Please enter a valid number": "有効な数値を入力してください",
  "Please enter a valid template.": "有効なテンプレートを入力してください。",
  "Please enter a valid width/height": "有効な幅/高さを入力してください",
  "Please select an image first": "まず画像を選択してください",
  "Please specify FFmpeg executable path first": "まずFFmpegの実行ファイルパスを指定してください",
  "PNG": "PNG",
  "PNGQUANT": "PNGQUANT",
  "Preset name": "プリセット名",
  "Preset name cannot be empty.": "プリセット名を空にすることはできません。",
  "Presets": "プリセット",
  "Preview": "プレビュー",
  "Preview:": "プレビュー:",
  "Process all images in vault": "保管庫内のすべての画像を処理",
  "Process all vault images": "保管庫全体の一括画像処理",
  "Process current note": "現在のノートを処理",
  "Process current note images": "現在のノートの画像処理",
  "Process folder": "フォルダを処理",
  "Process folder images": "フォルダ内の一括画像処理",
  "Process image": "画像を処理",
  "Process single image": "単一画像の処理",
  "Provide full-path to the binary file. It can be inside vault or anywhere in your file system.": "バイナリファイルへのフルパスを指定してください。保管庫内またはファイルシステム上の任意の場所を指定できます。",
  "Quality": "品質",
  "Quality range for pngquant": "pngquantの品質範囲",
  "Quality setting for pngquant (e.g., 65-80). Both min-max values must be provided.": "pngquantの品質設定（例: 65-80）。最小値と最大値の両方を指定する必要があります。",
  "Quality: {quality}": "品質: {quality}",
  "Rectangle (R)": "長方形 (R)",
  "Relative": "相対パス",
  "Relative:": "相対パス:",
  "Rename file": "ファイル名を変更",
  "Reset": "リセット",
  "Reset all": "すべてリセット",
  "Reset to default": "デフォルトに戻す",
  "Reset zoom": "ズームをリセット",
  "Resize": "リサイズ",
  "Resize dimension": "リサイズ寸法",
  "Resize mode": "リサイズモード",
  "Resize preset": "リサイズプリセット",
  "Resize presets": "リサイズプリセット",
  "Resize: {mode}": "リサイズ: {mode}",
  "Respect editor max width": "エディタの最大幅に制限",
  "Respect Editor Max Width: {val}": "エディタ最大幅に制限: {val}",
  "Revert to original if larger": "大きくなった場合は元画像に戻す",
  "Revert to original if larger: Yes": "大きくなった場合は元画像に戻す: はい",
  "Right": "右揃え",
  "Right-click menu": "右クリックメニュー",
  "Root folder": "ルートフォルダ",
  "Root folder of the vault (Top-level folder).": "保管庫のルートフォルダ（最上位階層）。",
  "Rotate": "回転",
  "Rotate 90°": "90°回転",
  "Same folder as current note": "現在のノートと同じフォルダ",
  "Same folder as the note you're currently editing.": "現在編集中のノートと同じフォルダ。",
  "Save": "保存",
  "Save as global preset": "グローバルプリセットとして保存",
  "Save as new preset": "新規プリセットとして保存",
  "Save changes": "変更を保存",
  "Save global preset": "グローバルプリセットを保存",
  "Save preset": "プリセットを保存",
  "Scale": "拡大縮小",
  "Scale mode": "拡大縮小モード",
  "Scale Mode: {mode}": "拡大縮小モード: {mode}",
  "Screen": "スクリーン",
  "Scroll-wheel modifier key": "スクロールホイールの修飾キー",
  "Scroll-wheel resize sensitivity": "スクロールホイールのリサイズ感度",
  "Search": "検索",
  "Search variables...": "変数を検索...",
  "Select all": "すべて選択",
  "Select an image to process": "処理する画像を選択してください",
  "Select preset": "プリセットを選択",
  "Send Backward": "背面へ移動",
  "Send to Back": "最背面へ移動",
  "Set both width and height using the format |widthxheight (e.g., 300x200) or percentage format (e.g., 50x75). This does not preserve aspect ratio.": "フォーマット |幅x高さ（例: 300x200）またはパーセンテージ形式（例: 50x75）で幅と高さの両方を指定します。この設定ではアスペクト比は維持されません。",
  "Set new custom height": "新しいカスタム高さを設定",
  "Set new custom width": "新しいカスタム幅を設定",
  "Set the maximum width of the image to fit within the editor's width. You can specify a percentage or a fixed pixel value.": "エディタの幅内に収まるよう画像の最大幅を設定します。パーセンテージまたは固定ピクセル値を指定できます。",
  "Settings": "設定",
  "Shortest": "最短パス",
  "Shortest edge": "短辺",
  "Shortest Edge": "短辺",
  "Shortest Edge: {edge}": "短辺: {edge}",
  "Shortest:": "最短パス:",
  "Show notification for image size changes": "画像サイズ変更の通知を表示",
  "Show notifications": "通知を表示",
  "Show window": "ウィンドウを表示",
  "Size:": "サイズ:",
  "Skip caption extensions": "キャプションを除外する拡張子",
  "Skip conversion patterns": "変換をスキップするパターン",
  "Skip Patterns: {patterns}": "スキップパターン: {patterns}",
  "Skip patterns": "スキップパターン",
  "Skip rename patterns": "リネームをスキップするパターン",
  "Skip rename patterns: {patterns}": "リネームをスキップするパターン: {patterns}",
  "Space at the top": "上部の余白",
  "Subfolder": "サブフォルダ",
  "Subfolder name": "サブフォルダ名",
  "Subfolder template": "サブフォルダテンプレート",
  "Summary": "概要",
  "Template": "テンプレート",
  "Template: {template}": "テンプレート: {template}",
  "Text alignment within caption": "キャプション内のテキスト配置",
  "Text transform": "テキストの大文字小文字変換",
  "This option allows you to further specify, how much the file size must be reduced before compressing the image. Sometimes an image's size might shrink by only 3 KB, but the visible degradation in quality is significant. This option helps catch those cases and avoids compressing such images. Default is 30kb, which means if after compressing the image file size would reduce only by 30kb or less, then the original image bytes will be used instead. Set to 0 to always allow compression when the output is smaller.": "画像を圧縮する際に必要な最小ファイル削減量を指定します。わずか3KBしか削減されないのに目に見える画質劣化が大きいケースを防ぐことができます。デフォルトは30KBで、圧縮後の削減量が30KB以下の場合は元画像がそのまま使用されます。出力が小さければ常に圧縮を許可する場合は0を設定してください。",
  "Transparent": "透明",
  "Type": "タイプ",
  "Undo (Ctrl+Z)": "元に戻す (Ctrl+Z)",
  "Unknown location": "不明な場所",
  "Uppercase": "大文字",
  "Use the path relative to the current note:": "現在のノートからの相対パスを使用:",
  "Uses just the file name without any path:": "パスを含まないファイル名のみを使用:",
  "Uses the complete path from your vault root, always starting with ": "保管庫のルートからの完全なパスを使用し、常に次の文字で始まります: ",
  "Validating...": "検証中...",
  "Variable": "変数",
  "Vault": "保管庫",
  "WEBP": "WEBP",
  "WEBP (75, no resizing)": "WEBP (品質75, リサイズなし)",
  "Weight": "フォントウェイト",
  "Width": "幅",
  "Width: {width}": "幅: {width}",
  "WidthxHeight (Custom)": "幅x高さ (カスタム)",
  "Wikilink": "内部リンク (Wikilink)",
  "Working encoder: ": "動作中のエンコーダー: ",
  "Yes": "はい",
  "Zoom in": "拡大",
  "Zoom out": "縮小",
  "Plugin automatically reads the original image dimensions and applies the provided value to the shorter of the width or height. The other dimension is then calculated automatically if 'maintain aspect ratio' is enabled.": "元の画像の寸法を自動取得し、幅または高さの短い方に指定値を適用します。「アスペクト比を維持」が有効な場合、もう一方の寸法は自動計算されます。",
  "Plugin automatically reads the original image dimensions and applies the provided value to the longer of the width or height. The other dimension is then calculated automatically if 'maintain aspect ratio' is enabled.": "元の画像の寸法を自動取得し、幅または高さの長い方に指定値を適用します。「アスペクト比を維持」が有効な場合、もう一方の寸法は自動計算されます。",
  "png,gif": "png,gif",
  "pngquant (Compression for PNG only))": "pngquant (PNG専用の高圧縮)",
  "pngquant (PNG Only)": "pngquant (PNG専用)",
  "Preserve the image's original proportions when resizing.": "リサイズ時に画像の元の縦横比（プロポーション）を維持します。",
  "Prevent accidental distortions of image aspect ratio when dragging to resize": "ドラッグによるリサイズ時の予期せぬアスペクト比の歪みを防止します",
  "Preview failed: {message}": "プレビュー生成に失敗しました: {message}",
  "Preview not available for this format.": "このフォーマットではプレビューを利用できません。",
  "Process": "処理実行",
  "Process all images": "すべての画像を処理",
  "Process all images in canvas": "キャンバス内のすべての画像を処理",
  "Process all images in current note": "現在のノート内のすべての画像を処理",
  "Process all images in folder": "フォルダ内のすべての画像を処理",
  "Process all images in note": "ノート内のすべての画像を処理",
  "Process Image: {name}": "画像の処理: {name}",
  "Process images in all subfolders as well": "すべてのサブフォルダ内の画像も処理対象に含める",
  "Processing image {current} of {total}, elapsed time: {time} seconds": "画像 {current} / {total} を処理中、経過時間: {time} 秒",
  "Processing images directly in the folder.": "フォルダ内の画像を直接処理します。",
  "Processing images linked in notes or Canvas files.": "ノートまたはキャンバスファイル内でリンクされている画像を処理します。",
  "Quality {quality}%": "品質 {quality}%",
  "Quality ⓘ": "品質 ⓘ",
  "Quality min-max range": "品質の最小・最大範囲",
  "Quickly apply a combination of presets": "プリセットの組み合わせを素早く適用",
  "r/^(drafts|scratch)\\// → Skips drafts/ and scratch/": "r/^(drafts|scratch)\\// → drafts/ と scratch/ をスキップ",
  "Recursive": "再帰的処理",
  "Reduce and enlarge": "縮小と拡大",
  "Reduce and enlarge: adjusts all images. Reduce only: shrinks larger images. Enlarge only: enlarges smaller images": "縮小と拡大: 全画像を調整。縮小のみ: より大きい画像を縮小。拡大のみ: より小さい画像を拡大",
  "Reduce and enlarge: Adjusts all images. Reduce only: Shrinks larger images. Enlarge only: Enlarges smaller images.": "縮小と拡大: 全画像を調整。縮小のみ: より大きい画像を縮小。拡大のみ: より小さい画像を拡大。",
  "Reduce only": "縮小のみ",
  "Reduce Only": "縮小のみ",
  "Regex is supported for advanced patterns": "高度なパターンには正規表現を使用可能",
  "regex:^media/(raw|temp)/ → Skips media/raw and media/temp": "regex:^media/(raw|temp)/ → media/raw と media/temp をスキップ",
  "Regular": "標準 (Regular)",
  "Reload plugin": "プラグインを再読み込み",
  "Reloading Image Converter...": "Image Converter を再読み込み中...",
  "Reset Zoom (1:1)": "ズームをリセット (1:1)",
  "Resize dimensions": "リサイズ寸法",
  "Resize Mode": "リサイズモード",
  "Resize mode ⓘ": "リサイズモード ⓘ",
  "Reuse existing file in vault (if any)": "保管庫内の既存ファイルを再利用（存在する場合）",
  "Reveal the Markdown link and keep focus in the editor when clicking an internal image in live preview, while hiding Obsidian's native outline, resize corner, and image action buttons. Cursor placement follows the drop/paste cursor position setting.": "ライブプレビューで内部画像をクリックした際にMarkdownリンクを展開してエディタにフォーカスを維持し、Obsidian標準のアウトラインやリサイズハンドル、操作ボタンを非表示にします。カーソル配置はドロップ/貼り付け設定に従います。",
  "Rotation: ": "回転: ",
  "Same as original": "元の形式を維持",
  "Same as original: preserves current format while applying compression/resizing": "元の形式を維持: 現在のフォーマットを保ったまま圧縮やリサイズを適用",
  "Same folder: starts with ": "同じフォルダ: 次の文字で始まります ",
  "Save (Ctrl/Cmd + S)": "保存 (Ctrl/Cmd + S)",
  "Save current selection as a new global preset": "現在の設定の組み合わせを新規グローバルプリセットとして保存",
  "Select": "選択",
  "Selected": "選択済み",
  "Semi-bold": "セミボールド (Semi-bold)",
  "Semi-transparent black": "半透明の黒",
  "Semi-transparent white": "半透明の白",
  "Set border radius for caption (e.g., make it slightly rounded: 4px)": "キャプションの枠線の角丸を設定します (例: 少し丸める場合は 4px)",
  "Set border style (e.g., 1px solid gray)": "枠線のスタイルを設定します (例: 1px solid gray)",
  "Set font weight (e.g., normal, bold, 600)": "フォントの太さを設定します (例: normal, bold, 600)",
  "Set padding around caption (e.g., 4px 8px)": "キャプション周囲のパディング（余白）を設定します (例: 4px 8px)",
  "Set space between image and caption (e.g., 4px, 8px)": "画像とキャプションの間の余白を設定します (例: 4px, 8px)",
  "Set text transformation": "テキストの大文字・小文字変換ルールを設定",
  "Set the font size for image captions (e.g., 12px, 1.2em).": "画像キャプションのフォントサイズを設定します (例: 12px, 1.2em)。",
  "Set the font style (e.g., italic, normal).": "フォントスタイルを設定します (例: italic, normal)。",
  "Show available variables": "利用可能な変数を表示",
  "Show examples and how matching works": "設定例と一致条件の仕組みを表示",
  "Show in navigation": "ナビゲーションに表示",
  "Show in system explorer": "システムエクスプローラーで表示",
  "Skip": "スキップ",
  "Skip compression/resizing if image is already in target format.": "画像が既に対象フォーマットである場合は圧縮やリサイズをスキップします。",
  "Skip file formats ⓘ": "除外する拡張子 ⓘ",
  "Skip folders ⓘ": "除外するフォルダ ⓘ",
  "Skip formats ⓘ": "除外するフォーマット ⓘ",
  "Skip images in target format ⓘ": "変換済みフォーマットの画像をスキップ ⓘ",
  "Skipped conversion of image \"{name}\" due to skip pattern match in the conversion preset.": "変換プリセットのスキップパターンに一致したため、画像「{name}」の変換をスキップしました。",
  "Skipped renaming/conversion of image \"{name}\" due to skip pattern match.": "スキップパターンに一致したため、画像「{name}」のリネーム/変換をスキップしました。",
  "Skipped: ": "スキップ: ",
  "Soft Light": "ソフトライト",
  "Subfolder template validation failed: {errors}": "サブフォルダテンプレートの検証に失敗しました: {errors}",
  "Subfolder: includes folder path (e.g., ": "サブフォルダ: フォルダパスを含めます (例: ",
  "Submit": "送信",
  "Supports multiple pattern types:\n\n1. Glob patterns:\n   *.png, draft-*, test-?.jpg\n   * = any characters\n   ? = single character\n\n2. Regular expressions:\n   /pattern/ or r/pattern/ or regex:pattern\n\nExamples:\n *.png (all PNG files)\n draft-* (files starting with draft-)\n /^IMG_\\d{4}\\./ (IMG_ followed by 4 digits)\n r/\\.(jpe?g|png)$/ (files ending in .jpg/.jpeg/.png)\n regex:^(draft|temp)- (files starting with draft- or temp-)": "複数のパターン形式に対応しています:\n\n1. Globパターン:\n   *.png, draft-*, test-?.jpg\n   * = 任意の文字列\n   ? = 任意の1文字\n\n2. 正規表現:\n   /pattern/ または r/pattern/ または regex:pattern\n\n例:\n *.png (すべてのPNGファイル)\n draft-* (draft- で始まるファイル)\n /^IMG_\\d{4}\\./ (IMG_ に続く4桁の数字)\n r/\\.(jpe?g|png)$/ (.jpg/.jpeg/.png で終わるファイル)\n regex:^(draft|temp)- (draft- または temp- で始まるファイル)",
  "Temporarily overwrite path defined in selected preset e.g.: assets/{YYYY}/{MM}": "選択中のプリセットで定義されたパスを一時的に上書きします（例: assets/{YYYY}/{MM}）",
  "Text Background:": "テキスト背景:",
  "The pngquant executable path is not set. Please configure it in the plugin settings.": "pngquantの実行ファイルパスが設定されていません。プラグイン設定で設定してください。",
  "their original": "元の形式",
  "This creates a new <DIV> under the image to show resizing HANDLES. But this might cause some incompatibility with certain themes and cause images to jump around.": "画像の下にリサイズ用ハンドルを表示する新しい<div>を作成します。ただし、一部のテーマとの互換性により画像の位置がずれる場合があります。",
  "To be processed: ": "処理対象: ",
  "To be skipped: ": "スキップ対象: ",
  "Total images found: ": "検出された画像の総数: ",
  "Unable to extract filename from the image source": "画像ソースからファイル名を抽出できませんでした",
  "Unable to find image: {filename}": "画像が見つかりません: {filename}",
  "Unable to locate image file": "画像ファイルを見つけることができませんでした",
  "Unable to open settings.": "設定を開くことができませんでした。",
  "Unable to open settings. Please check if the settings plugin is enabled.": "設定を開くことができませんでした。設定プラグインが有効になっているか確認してください。",
  "Update": "更新",
  "UPPERCASE": "すべて大文字",
  "Use * to match only direct children": "* を使用して直下の階層のみに一致",
  "Use ** to include subfolders too": "** を使用してサブフォルダも含めて一致",
  "Uses the path relative to the current note:": "現在のノートからの相対パスを使用:",
  "Using original image for \"{name}\" as processed image is larger.": "処理後の画像の方が大きいため、「{name}」には元画像を使用します。",
  "Using original image for \"{name}\" because size reduction was less than {minSavingsKB} KB.": "サイズ削減量が {minSavingsKB} KB 未満だったため、「{name}」には元画像を使用します。",
  "W": "幅",
  "Warning: Inconsistent folder casing detected. Using original path: {path}": "警告: フォルダ名の大文字・小文字の不一致が検出されました。元のパスを使用します: {path}",
  "When calculating dimensions, prevent the image from exceeding the editor's width.": "寸法計算時に画像がエディタの幅を超えないように制限します。",
  "Where to place the cursor after dropping or pasting the image": "画像のドロップまたは貼り付け後のカーソル配置場所",
  "Where to place the cursor when resizing an image. Note: 'don't move cursor' - will try to keep your exisiting cursor in place but if you DRAG-RESIZE and cursor is still over the image when you finish resizing, it will get the text selected.": "画像のリサイズ時にカーソルを配置する場所。（注意:「カーソルを移動しない」は現在の位置を維持しようとしますが、ドラッグ終了時にカーソルが画像上にあるとテキストが選択状態になる場合があります）",
  "Within config folder (syncable)": "設定フォルダ内 (.obsidian内 / 同期可能)",
  "Within plugin folder (not syncable)": "プラグインフォルダ内 (同期非推奨)",
  "Zoom: ": "ズーム: ",
  "Comma-separated folder patterns to exclude images from processing.": "処理から除外するフォルダパターンのカンマ区切りリスト。",
  "Comma-separated list (no dots or spaces, e.g., png,gif).": "カンマ区切りリスト（ドットやスペースなし、例: png,gif）。",
  "Comma-separated list (no dots or spaces). Example: png,gif": "カンマ区切りリスト（ドットやスペースなし）。例: png,gif",
  "Comma-separated list of file formats to skip (e.g., tif,tiff,heic). Leave empty to process all formats.": "除外する画像形式のカンマ区切りリスト（例: tif,tiff,heic）。空にするとすべての形式を処理します。",
  "Comma-separated list of image extensions to exclude from captions (e.g., PNG, JPG).": "キャプションから除外する画像拡張子のカンマ区切りリスト（例: PNG, JPG）。",
  "Compression level (0-100)": "圧縮レベル (0〜100)",
  "Configure non-destructive resizing options for images directly within the editor. This allows to adjust the display size without altering the original file.": "エディタ内で画像の非破壊リサイズオプションを設定します。元の画像ファイルを変更せずに表示サイズのみを調整できます。",
  "Confirm Cut": "切り取りの確認",
  "Confirm Delete": "削除の確認",
  "Confirm Updates": "更新の確認",
  "Context menu disabled. Reload Obsidian to see changes.": "コンテキストメニューを無効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Context menu enabled. Reload Obsidian to see changes.": "コンテキストメニューを有効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Control how converted images are named. Use variables like {notename}, {timestamp}, {uuid}, or {MD5:filename} to create unique filenames.": "変換後の画像の名前付けルールを設定します。{notename}、{timestamp}、{uuid}、{MD5:filename} などの変数を使用して一意のファイル名を作成できます。",
  "Control the output format, quality, and resizing options for converted images. This allows to significantly reduce file size and keep vault size small.": "変換後の画像の出力フォーマット、品質、リサイズオプションを制御します。ファイルサイズを大幅に削減し、保管庫のサイズを軽量に保つことができます。",
  "Controls how images are adjusted relative to target size:": "指定サイズに対する画像の調整方法を制御します:",
  "Controls how images are adjusted relative to target size:\\n- Auto: adjusts image to fit specified dimensions\\n- Reduce only: only shrinks images larger than target\\n- Enlarge only: only enlarges images smaller than target": "指定サイズに対する画像の調整方法を制御します:\n- 自動: 指定サイズに合わせて画像を調整\n- 縮小のみ: 指定サイズより大きい画像のみを縮小\n- 拡大のみ: 指定サイズより小さい画像のみを拡大",
  "Convert to ⓘ": "変換先 ⓘ",
  "Convert to ⓘ ": "変換先 ⓘ ",
  "Convert, compress and resize": "変換・圧縮・リサイズ",
  "Convert, compress and resize all images": "すべての画像を変換・圧縮・リサイズ",
  "Convert/compress...": "変換/圧縮...",
  "Copy as Base64 encoded image": "Base64エンコード画像としてコピー",
  "Copy image": "画像をコピー",
  "Crop/rotate/flip": "トリミング/回転/反転",
  "Custom folder template is not defined.": "カスタムフォルダテンプレートが定義されていません。",
  "Custom template": "カスタムテンプレート",
  "Cut": "切り取り",
  "Darken": "比較(暗)",
  "Default (Obsidian setting)": "デフォルト (Obsidian設定に従う)",
  "Default (Using Obsidian's configured setting for attachments)": "デフォルト (Obsidianのアタッチメント設定を使用)",
  "Default (Wikilink, Shortest)": "デフォルト (Wikilink, 最短パス)",
  "Default (No Resize)": "デフォルト (リサイズなし)",
  "Default alignment for new images": "新規画像のデフォルト配置",
  "Define where converted images will be stored. Choose from predefined locations or create custom paths using variables.": "変換後の画像の保存先を定義します。事前定義された保存先から選択するか、変数を使用してカスタムパスを作成できます。",
  "Delete": "削除",
  "Delete image and link": "画像とリンクを削除",
  "Delete selected global preset": "選択したグローバルプリセットを削除",
  "Description": "説明",
  "Desired Height": "希望する高さ",
  "Desired Longest Edge": "希望する長辺",
  "Desired Shortest Edge": "希望する短辺",
  "Desired Width": "希望する幅",
  "Determine how image links are inserted into notes. Choose between Wikilinks and Markdown links, and specify how the file path should be formatted. This allows to use a different link style for images than your vault's default, offering better cross-compatibility with other applications.": "ノートへの画像リンクの挿入方法を決定します。内部リンク（Wikilink）とMarkdownリンクを選択し、パスのフォーマットを指定できます。保管庫のデフォルトとは異なるリンクスタイルを使用でき、他アプリケーションとの互換性を向上させます。",
  "Difference": "差の絶対値",
  "Dimensions must be positive numbers": "寸法は正の数値である必要があります",
  "Direct images": "フォルダ直下の画像",
  "Display a notification showing how much space was saved after processing an image.": "画像処理後に削減されたファイル容量を示す通知を表示します。",
  "Dodge": "覆い焼き",
  "Don't move cursor": "カーソルを移動しない",
  "Duplicate preset": "プリセットを複製",
  "Edit": "編集",
  "Edit image in default app": "既定のアプリで画像を編集",
  "Edit preset": "プリセットを編集",
  "Enter custom name": "カスタム名を入力",
  "Enter image name": "画像名を入力",
  "Enter regular expression": "正規表現を入力",
  "Enter valid number": "有効な数値を入力してください",
  "Exclusion list": "除外リスト",
  "Exclusion patterns": "除外パターン",
  "Failed to load image": "画像の読み込みに失敗しました",
  "Filename conflict": "ファイル名の競合",
  "Filename conflict resolution": "ファイル名競合時の解決方法",
  "Filename Template Validation": "ファイル名テンプレートの検証",
  "Filter": "フィルター",
  "General settings": "一般設定",
  "Global preset": "グローバルプリセット",
  "Global Preset": "グローバルプリセット",
  "Global presets": "グローバルプリセット",
  "Image": "画像",
  "Image Actions": "画像アクション",
  "Image alignment": "画像の配置",
  "Image dimensions (WxH)": "画像の寸法 (幅x高さ)",
  "Image format": "画像フォーマット",
  "Image name": "画像名",
  "Image name template": "画像名テンプレート",
  "Image quality": "画質",
  "Images": "画像",
  "Include subfolders": "サブフォルダを含める",
  "Include subfolders (recursive)": "サブフォルダを含める (再帰処理)",
  "Invalid filename": "無効なファイル名です",
  "Invalid folder path": "無効なフォルダパスです",
  "Invalid quality value": "無効な品質値です",
  "Lighten": "比較(明)",
  "Link Format Presets": "リンク形式プリセット",
  "Link style": "リンクスタイル",
  "Linked images": "リンクされている画像",
  "Loading...": "読み込み中...",
  "Markdown, Relative": "Markdown, 相対パス",
  "Match whole word": "単語全体に一致",
  "Modal": "モーダル",
  "Move to cursor": "カーソル位置へ移動",
  "Name": "名前",
  "Next": "次へ",
  "No images to process": "処理する画像がありません",
  "None (keep original)": "なし (元画像を維持)",
  "Non-destructive resize": "非破壊リサイズ",
  "Non-destructive Resize": "非破壊リサイズ",
  "Not set": "未設定",
  "Number of images": "画像数",
  "Open image": "画像を開く",
  "Original": "オリジナル",
  "Original dimensions": "元の寸法",
  "Original format": "元のフォーマット",
  "Output": "出力",
  "Output Directory": "出力ディレクトリ",
  "Output folder": "出力フォルダ",
  "Output Format": "出力フォーマット",
  "Overlay": "オーバーレイ",
  "Path": "パス",
  "Percentage": "パーセンテージ",
  "Position": "位置",
  "Preset": "プリセット",
  "Preset Name": "プリセット名",
  "Presets saved": "プリセットを保存しました",
  "Previous": "前へ",
  "Process All": "すべて処理",
  "Processing...": "処理中...",
  "Quality (0-100)": "品質 (0〜100)",
  "Quality range": "品質範囲",
  "Ready": "準備完了",
  "Reload": "再読み込み",
  "Rename": "名前を変更",
  "Replace": "置換",
  "Resize Dimensions": "リサイズ寸法",
  "Save as Preset": "プリセットとして保存",
  "Save Preset": "プリセットを保存",
  "Saved": "保存完了",
  "Scanning vault for images...": "保管庫内の画像をスキャン中...",
  "Select All": "すべて選択",
  "Select Folder": "フォルダを選択",
  "Select Preset": "プリセットを選択",
  "Selected folder: {folder}": "選択したフォルダ: {folder}",
  "Settings for": "設定対象:",
  "Skip conversion": "変換をスキップ",
  "Skip existing": "既存のファイルをスキップ",
  "Skip folder": "フォルダをスキップ",
  "Skip images": "画像を除外",
  "Skip Rename": "リネームをスキップ",
  "Start": "開始",
  "Status": "ステータス",
  "Success": "成功",
  "Target format": "変換先フォーマット",
  "Total images": "画像総数",
  "Units": "単位",
  "Value": "値",
  "Vault root": "保管庫ルート",
  "Variables": "変数",
  "View": "表示",
  "Warning": "警告",
  "Width and Height": "幅と高さ",
  "px": "px",
  "%": "%",
  "Example: {path}": "例: {path}",
  "Example: loading...": "例: 読み込み中...",
  "Example: error generating preview": "例: プレビュー生成エラー",
  "Example:": "例:",
  "No variables found matching \"{searchTerm}\"": "「{searchTerm}」に一致する変数は見つかりませんでした",
  "e.g., *.png, draft-*, /^IMG_\\d{4}\\./)": "例: *.png, draft-*, /^IMG_\\d{4}\\./",
  "e.g. 50x75": "例: 50x75",
  "widthxheight": "幅x高さ",
  "e.g. 50%": "例: 50%",
  "e.g. 200px": "例: 200px",

  // 追加キーの完全網羅
  "Example": "例",
  "Example: png,gif": "例: png,gif",
  "Exclusion": "除外",
  "Failed to copy image as Base64": "Base64としての画像コピーに失敗しました",
  "Failed to copy image to clipboard": "クリップボードへの画像コピーに失敗しました",
  "Failed to create folder \"{path}\". Check console for details.": "フォルダ「{path}」の作成に失敗しました。詳細はコンソールを確認してください。",
  "Failed to cut image. Check console for details.": "画像の切り取りに失敗しました。詳細はコンソールを確認してください。",
  "Failed to cut. See console for details.": "切り取りに失敗しました。詳細はコンソールを確認してください。",
  "Failed to delete image. Check console for details.": "画像の削除に失敗しました。詳細はコンソールを確認してください。",
  "Failed to delete. See console for details.": "削除に失敗しました。詳細はコンソールを確認してください。",
  "Failed to determine destination or filename for \"{name}\". Check console for details.": "「{name}」の保存先またはファイル名の決定に失敗しました。詳細はコンソールを確認してください。",
  "Failed to export image": "画像のエクスポートに失敗しました",
  "Failed to find Base64 image link": "Base64画像リンクが見つかりませんでした",
  "Failed to find image link in the current note.": "現在のノート内で画像リンクが見つかりませんでした。",
  "Failed to find unique image links in the current note.": "現在のノート内で一意な画像リンクが見つかりませんでした。",
  "Failed to get canvas context": "Canvasコンテキストの取得に失敗しました",
  "Failed to insert image link. Check console for details.": "画像リンクの挿入に失敗しました。詳細はコンソールを確認してください。",
  "Failed to insert link for \"{name}\". Check console for details.": "「{name}」のリンク挿入に失敗しました。詳細はコンソールを確認してください。",
  "Failed to load image dimensions for {name}": "「{name}」の画像寸法の読み込みに失敗しました",
  "Failed to load image for base64 copy": "Base64コピー用画像の読み込みに失敗しました",
  "Failed to load image for clipboard": "クリップボード用画像の読み込みに失敗しました",
  "Failed to open in new window": "新しいウィンドウで開くのに失敗しました",
  "Failed to process image \"{name}\" (target: {format}): {message}": "画像「{name}」の処理に失敗しました (変換先: {format}): {message}",
  "Failed to process image \"{name}\": {message}. Check console for details.": "画像「{name}」の処理に失敗しました: {message}。詳細はコンソールを確認してください。",
  "Failed to process image \"{name}\". Check console for details.": "画像「{name}」の処理に失敗しました。詳細はコンソールを確認してください。",
  "Failed to process image: File \"{filename}\" already exists.": "画像の処理に失敗しました: ファイル「{filename}」は既に存在します。",
  "Failed to process image: Invalid input file type for \"{name}\".": "画像の処理に失敗しました: 「{name}」の入力ファイル形式が無効です。",
  "Failed to reload plugin, see console": "プラグインの再読み込みに失敗しました。コンソールを確認してください",
  "Failed to reload: plugins API unavailable": "再読み込み失敗: プラグインAPIが利用できません",
  "Failed to show in navigation": "ナビゲーションでの表示に失敗しました",
  "Failed to show in system explorer": "システムエクスプローラーでの表示に失敗しました",
  "Failed to update image path": "画像パスの更新に失敗しました",
  "Failed to update links for \"{name}\". Check console for details.": "「{name}」のリンク更新に失敗しました。詳細はコンソールを確認してください。",
  "Failed to update links in note for \"{name}\". Check console for details.": "ノート内の「{name}」のリンク更新に失敗しました。詳細はコンソールを確認してください。",
  "Failed to update. See console for details.": "更新に失敗しました。詳細はコンソールを確認してください。",
  "FFmpeg CRF: {crf}": "FFmpeg CRF: {crf}",
  "FFmpeg executable path is not set. Please configure it in the plugin settings.": "FFmpegの実行ファイルパスが設定されていません。プラグイン設定で設定してください。",
  "Filename template validation failed: {errors}": "ファイル名テンプレートの検証に失敗しました: {errors}",
  "Fill (exactly match dimensions)": "塗りつぶし (指定寸法に完全一致)",
  "Finished processing {count} images, total time: {time} seconds": "{count} 件の画像の処理が完了しました、総所要時間: {time} 秒",
  "Fit (maintain aspect ratio within dimensions)": "全体を収める (寸法内でアスペクト比を維持)",
  "Fit: maintains aspect ratio within dimensions\\nFill: exactly matches dimensions\\nLongest edge: limits the longest side\\nShortest edge: limits the shortest side\\nWidth/height: constrains single dimension": "Fit: 寸法内でアスペクト比を維持\nFill: 指定寸法に完全一致\n長辺: 長い方の辺を制限\n短辺: 短い方の辺を制限\n幅/高さ: 単一の寸法に制限",
  "Fit: Maintains aspect ratio within dimensions\\nFill: Exactly matches dimensions\\nLongest edge: Limits the longest side\\nShortest edge: Limits the shortest side\\nWidth/Height: Constrains single dimension": "Fit: 寸法内でアスペクト比を維持\nFill: 指定寸法に完全一致\n長辺: 長い方の辺を制限\n短辺: 短い方の辺を制限\n幅/高さ: 単一の寸法に制限",
  "Fit: Maintains aspect ratio within dimensions\\nFill: Exactly matches dimensions\\nLongest Edge: Limits the longest side\\nShortest Edge: Limits the shortest side\\nWidth/Height: Constrains single dimension": "Fit: 寸法内でアスペクト比を維持\nFill: 指定寸法に完全一致\n長辺: 長い方の辺を制限\n短辺: 短い方の辺を制限\n幅/高さ: 単一の寸法に制限",
  "Flip horizontally": "左右反転",
  "Flip vertically": "上下反転",
  "Folder paths without wildcards skip that folder and all subfolders": "ワイルドカードなしのフォルダパスは、そのフォルダとすべてのサブフォルダをスキップします",
  "Folder template validation failed: {errors}": "フォルダテンプレートの検証に失敗しました: {errors}",
  "Folder:": "フォルダ:",
  "Found {count} matching image links inside current note. Do you want to cut all of them?": "現在のノート内で一致する画像リンクが {count} 件見つかりました。すべて切り取りますか？",
  "Found {count} matching image links. Update all?": "一致する画像リンクが {count} 件見つかりました。すべて更新しますか？",
  "Found {count} unique matching image links inside current note. Do you want to delete all of them?": "現在のノート内で一致する一意な画像リンクが {count} 件見つかりました。すべて削除しますか？",
  "Free": "自由",
  "General": "一般",
  "Generating preview...": "プレビューを生成中...",
  "Grayscale:": "グレースケール:",
  "H": "高さ",
  "Hard Light": "ハードライト",
  "Hardware encoder unavailable. Falling back to {encoder}...": "ハードウェアエンコーダーが使用できません。{encoder} にフォールバックします...",
  "How matching works:": "一致条件の仕組み:",
  "If image is already in target format, this allows you to skip its compression, conversion and resizing. Processing of all other formats will be still performed.": "画像が既に対象フォーマットである場合、その圧縮・変換・リサイズをスキップできます。その他のフォーマットの処理は通常通り実行されます。",
  "If you use Obsidian Sync, it is strongly recommended to use the SAME location on all your devices to ensure consistent behavior. Default: Obsidian's config folder (syncable).": "Obsidian Sync を使用している場合、すべてのデバイスで動作の一貫性を保つため同じ保存場所を使用することを強く推奨します。デフォルト: Obsidianの設定フォルダ（同期可能）。",
  "Image \"{name}\" processed": "画像「{name}」を処理しました",
  "Image alignment disabled. Reload Obsidian to see changes.": "画像の配置を無効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image alignment enabled. Reload Obsidian to see changes.": "画像の配置を有効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image caption and dimensions updated successfully.": "画像キャプションと寸法を正常に更新しました。",
  "Image captions disabled. Reload Obsidian to see changes.": "画像キャプションを無効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image captions enabled. Reload Obsidian to see changes.": "画像キャプションを有効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image Converter reloaded!": "Image Converter を再読み込みしました！",
  "Image Converter: Failed to initialize. Check console for details.": "Image Converter: 初期化に失敗しました。詳細はコンソールを確認してください。",
  "Image copied to clipboard": "画像をクリップボードにコピーしました",
  "Image copied to clipboard as Base64": "画像をBase64としてクリップボードにコピーしました",
  "Image dimensions updated successfully.": "画像寸法を正常に更新しました。",
  "Image file moved to trash": "画像ファイルをゴミ箱へ移動しました",
  "Image link(s) cut from note and copied to clipboard": "ノートから画像リンクを切り取り、クリップボードにコピーしました",
  "Image link(s) removed from note": "ノートから画像リンクを削除しました",
  "Image name updated successfully": "画像名を正常に更新しました",
  "Image not added: the destination path is too long for Windows ({length} characters). Paths must be shorter than {limit} characters. Shorten the destination folder or filename.\\n{absolutePath}": "画像を追加できませんでした: Windowsのパス長制限を超えています（{length} 文字）。パスは {limit} 文字未満にする必要があります。保存先フォルダまたはファイル名を短くしてください。\n{absolutePath}",
  "Image path update failed (case-sensitive change).": "画像パスの更新に失敗しました（大文字小文字の変更）。",
  "Image path updated (case-sensitive change).": "画像パスを更新しました（大文字小文字の変更）。",
  "Image path updated successfully": "画像パスを正常に更新しました",
  "Image processed, but failed to refresh view. You may need to reload the note.": "画像を処理しましたが、ビューの更新に失敗しました。ノートの再読み込みが必要な場合があります。",
  "Image resizing disabled. Reload Obsidian to see changes.": "画像のリサイズを無効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image resizing enabled. Reload Obsidian to see changes.": "画像のリサイズを有効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Image saved successfully": "画像を正常に保存しました",
  "Image source": "画像ソース",
  "Image tools": "画像ツール",
  "Images directly in the folder": "フォルダ直下の画像",
  "Images linked in notes or Canvas": "ノートまたはキャンバス内でリンクされている画像",
  "images/**, assets/** → Skips multiple folder trees": "images/**, assets/** → 複数のフォルダツリー全体をスキップ",
  "In subfolder under current note": "現在のノート直下のサブフォルダ内",
  "In the vault": "保管庫内",
  "Instructs pngquant to use the least amount of colors required to meet or exceed the max quality. min and max are numbers in range 0 (worst) to 100 (perfect).": "最高品質を満たすか上回るために必要な最小限の色数を使用するよう pngquant に指示します。min と max は 0（最低）から 100（最高）の範囲の数値です。",
  "Interval (in minutes) to clean up redundant entries from image alignment cache. Default: 1 hour (0 to disable)": "画像配置キャッシュから冗長なエントリをクリーンアップする間隔（分単位）。デフォルト: 1時間（0で無効化）",
  "Key that must be held while using scroll-wheel to resize": "スクロールホイールでリサイズする際に押す修飾キー",
  "Layer:": "レイヤー:",
  "Leading / is optional": "先頭の / は省略可能",
  "Light": "細字 (Light)",
  "Link": "リンク",
  "Link updated in \"{name}\"": "「{name}」内のリンクを更新しました",
  "Loading caption...": "キャプションを読み込み中...",
  "lowercase": "小文字",
  "Name:": "名前:",
  "Never show": "表示しない",
  "No active file detected": "アクティブなファイルが検出されませんでした",
  "No active Markdown view": "アクティブなMarkdownビューがありません",
  "No active Markdown view found": "アクティブなMarkdownビューが見つかりません",
  "No AV1 encoder found in FFmpeg. Please install FFmpeg with AV1 support (libaom-av1, libsvtav1, or hardware encoder).": "FFmpeg内にAV1エンコーダーが見つかりませんでした。AV1対応のFFmpeg（libaom-av1、libsvtav1、またはハードウェアエンコーダー）をインストールしてください。",
  "No current file found": "現在のファイルが見つかりません",
  "No images found in the folder.": "フォルダ内に画像が見つかりませんでした。",
  "No images found in the note.": "ノート内に画像が見つかりませんでした。",
  "No images found in the vault.": "保管庫内に画像が見つかりませんでした。",
  "No images found that need processing.": "処理が必要な画像は見つかりませんでした。",
  "No path specified": "パスが指定されていません",
  "No processing needed for \"{name}\".": "「{name}」の処理は不要です。",
  "No processing needed: All images are already in {format} format.": "処理不要: すべての画像が既に {format} フォーマットです。",
  "No processing needed: All images are either in skip list or already in {format} format with no compression or resizing.": "処理不要: すべての画像が除外リストに含まれているか、既に {format} フォーマットで圧縮・リサイズの設定がありません。",
  "No processing needed: all images are either in skip list or kept in original format with no compression or resizing.": "処理不要: すべての画像が除外リストに含まれているか、圧縮・リサイズなしで元のフォーマットが維持されています。",
  "No processing needed: All vault images are either in {format} format or in skip list.": "処理不要: 保管庫内のすべての画像が既に {format} フォーマットであるか除外リストに含まれています。",
  "No processing needed: all vault images are either in skip list or already in {format} format with no compression or resizing.": "処理不要: 保管庫内のすべての画像が除外リストに含まれているか、既に {format} フォーマットで圧縮・リサイズの設定がありません。",
  "No processing needed: all vault images are either in skip list or kept in original format with no compression or resizing.": "処理不要: 保管庫内のすべての画像が除外リストに含まれているか、圧縮・リサイズなしで元のフォーマットが維持されています。",
  "No processing needed: original format selected with no compression or resizing.": "処理不要: 圧縮・リサイズなしで元のフォーマットが選択されています。",
  "No selection.": "選択されていません。",
  "No source attribute found": "ソース属性が見つかりません",
  "No source attribute found on the image": "画像上にソース属性が見つかりません",
  "No unique image links found to delete.": "削除対象の一意な画像リンクが見つかりませんでした。",
  "Non-destructive resizing in reading mode is only visual, thus if it is too distractive you can disable it.": "閲覧モードでの非破壊リサイズは表示上のみの調整です。気になる場合は無効にできます。",
  "None (No Conversion)": "なし (変換なし)",
  "None (No Conversion/Compression)": "なし (変換・圧縮なし)",
  "Not a valid image file": "有効な画像ファイルではありません",
  "Obsidian image selection disabled. Reload Obsidian to see changes.": "Obsidian標準の画像選択を無効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Obsidian image selection enabled. Reload Obsidian to see changes.": "Obsidian標準の画像選択を有効化しました。変更を適用するにはObsidianを再読み込みしてください。",
  "Open Image Converter Settings": "Image Converter 設定を開く",
  "Open in new window": "新しいウィンドウで開く",
  "Original (Compress)": "元の形式 (圧縮)",
  "Palette:": "パレット:",
  "Parent folder: starts with ": "親フォルダ: 次の文字で始まります ",
  "Please enter a new file name.": "新しいファイル名を入力してください。",
  "Please enter a new path.": "新しいパスを入力してください。",
  "Please enter a valid file name": "有効なファイル名を入力してください",
  "r/^(drafts|scratch)\\\\// → Skips drafts/ and scratch/": "r/^(drafts|scratch)\\\\// → drafts/ と scratch/ をスキップ",
  "Supports multiple pattern types:\\n\\n1. Glob patterns:\\n   *.png, draft-*, test-?.jpg\\n   * = any characters\\n   ? = single character\\n\\n2. Regular expressions:\\n   /pattern/ or r/pattern/ or regex:pattern\\n\\nExamples:\\n *.png (all PNG files)\\n draft-* (files starting with draft-)\\n /^IMG_\\\\d{4}\\\\./ (IMG_ followed by 4 digits)\\n r/\\\\.(jpe?g|png)$/ (files ending in .jpg/.jpeg/.png)\\n regex:^(draft|temp)- (files starting with draft- or temp-)": "複数のパターン形式に対応しています:\n\n1. Globパターン:\n   *.png, draft-*, test-?.jpg\n   * = 任意の文字列\n   ? = 任意の1文字\n\n2. 正規表現:\n   /pattern/ または r/pattern/ または regex:pattern\n\n例:\n *.png (すべてのPNGファイル)\n draft-* (draft- で始まるファイル)\n /^IMG_\\d{4}\\./ (IMG_ に続く4桁の数字)\n r/\\.(jpe?g|png)$/ (.jpg/.jpeg/.png で終わるファイル)\n regex:^(draft|temp)- (draft- または temp- で始まるファイル)",

  // 残りの45キー
  "Dominant:": "主要色:",
  "Don't move Cursor": "カーソルを移動しない",
  "Drag & scroll resize": "ドラッグ＆スクロールリサイズ",
  "Draw (B)": "描画 (B)",
  "Drop/paste presets": "ドロップ/貼り付けプリセット",
  "e.g., _attachments, images/**": "例: _attachments, images/**",
  "e.g., {imagename}-{timestamp}": "例: {imagename}-{timestamp}",
  "e.g., {notename}-{timestamp}": "例: {notename}-{timestamp}",
  "e.g., {YYYY}/{MM}/{imagename}": "例: {YYYY}/{MM}/{imagename}",
  "e.g., *.png, draft-*, /^IMG_\\\\d{4}\\\\./)": "例: *.png, draft-*, /^IMG_\\d{4}\\./",
  "e.g., tif, tiff, heic": "例: tif, tiff, heic",
  "Edit presets": "プリセットを編集",
  "Enable to show a right-click context menu.": "右クリックコンテキストメニューの表示を有効にします。",
  "Encoder detection failed. Using cached encoder: {cachedEncoder}{platformHint}": "エンコーダーの検出に失敗しました。キャッシュされたエンコーダーを使用します: {cachedEncoder}{platformHint}",
  "Enlarge only": "拡大のみ",
  "Enlarge or reduce ⓘ": "拡大または縮小 ⓘ",
  "Enlarge/Reduce": "拡大/縮小",
  "Enter a custom caption": "カスタムキャプションを入力",
  "Enter a custom path.": "カスタムパスを入力してください。",
  "Enter a custom subfolder name or path.": "カスタムサブフォルダ名またはパスを入力してください。",
  "Enter a new image name": "新しい画像名を入力",
  "Enter a new path for the image": "画像の新しいパスを入力",
  "Enter quality (0-100)": "品質を入力 (0〜100)",
  "Enter templates to see preview": "プレビューを表示するにはテンプレートを入力してください",
  "Enter the desired height in pixels": "希望する高さをピクセル単位で入力",
  "Enter the desired length in pixels": "希望する長さをピクセル単位で入力",
  "Enter the desired width and height in pixels": "希望する幅と高さをピクセル単位で入力",
  "Enter the desired width in pixels": "希望する幅をピクセル単位で入力",
  "Error generating preview": "プレビュー生成エラー",
  "Error incrementing filename for \"{name}\". Check console for details.": "「{name}」のファイル名連番処理でエラーが発生しました。詳細はコンソールを確認してください。",
  "Error loading image": "画像の読み込みエラー",
  "Error loading image for cropping": "トリミング用画像の読み込みエラー",
  "Error processing image": "画像処理エラー",
  "Error processing image \"{name}\": {message}": "画像「{name}」の処理エラー: {message}",
  "Error processing image path": "画像パスの処理エラー",
  "Error processing images: {message}": "画像の一括処理エラー: {message}",
  "Error renaming file: {message}": "ファイル名変更エラー: {message}",
  "Error saving image": "画像保存エラー",
  "Error saving image: {message}": "画像の保存エラー: {message}",
  "Error: active file must be a markdown or canvas file.": "エラー: アクティブなファイルはMarkdownまたはCanvasファイルである必要があります。",
  "Error: Could not find renamed file at {path}": "エラー: 名前変更されたファイルが {path} に見つかりませんでした",
  "Error: invalid folder path.": "エラー: 無効なフォルダパスです。",
  "Error: Invalid folder path.": "エラー: 無効なフォルダパスです。",
  "Error: temporary file not found after renaming.": "エラー: 名前変更後に一時ファイルが見つかりませんでした。",
  "Preset {num} saved": "プリセット {num} を保存しました"
};

const jaDict = {};
let missing = [];

for (const [key, enVal] of Object.entries(en)) {
  if (manualTranslations[key]) {
    jaDict[key] = manualTranslations[key];
  } else if (/^Preset \d+ saved$/.test(key)) {
    const num = key.match(/\d+/)[0];
    jaDict[key] = `プリセット ${num} を保存しました`;
  } else {
    // 汎用自動マッチング
    missing.push(key);
    jaDict[key] = enVal;
  }
}

if (missing.length > 0) {
  console.log(`Missing ${missing.length} keys:`);
  console.log(JSON.stringify(missing, null, 2));
} else {
  console.log('All 632 keys perfectly matched and translated!');
}

fs.writeFileSync(jaPath, JSON.stringify(jaDict, null, 2) + '\n', 'utf-8');
console.log('Saved ja.json');
